### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'serialize'

### ISSUE THREAD

**Issue by uniyushu** [ifzhang/ByteTrack#116]
I try to convert bytetrack model on jetson nano, but meet AttributeError: 'NoneType' object has no attribute 'serialize' issues. 
I have tried the nano and s models. Any help?
![image](https://user-images.githubusercontent.com/20262193/147064934-c72dc594-b784-4cd0-8fae-6d9499ae5565.png)
![image](https://user-images.githubusercontent.com/20262193/147065694-a00c6ac5-c237-40d8-b59b-d044194816ce.png)

**Comment by LamnouarMohamed** [comment]
Any solution for that problem ?

**Comment by uniyushu** [comment]
> Any solution for that problem ?

I try trtexec command, solve this problem.the code like
`trtexec --onnx=bytetrack_s.onnx --saveEngine=bytetrack_s_best.engine --best`

**Comment by LamnouarMohamed** [comment]
Thank you so much for reply,

 I have test this solution, and the output of this command give me one output is bytetrack_l_best.engine, but the tools/demo_track.py it's need to two files first ".enigne" and second ".pth" how Can I solve this problem ?
