### ISSUE TITLE
Tracking disappear when detect vehicles.

### ISSUE THREAD

**Issue by xiefengan** [ifzhang/ByteTrack#120]
I have a problem is about that using ByteTrack in Multiple Class Multiple Object Tracking,
I am using my trained yolov5 as a backbone detector to detect objects on road, including vehicle, bicycle, person, and so on.
My detector can detect objects perfectly, But some bounding box of Vehicle will disappear after match stage,
but they all have high scores from detection stage, and i tried to modify the  sort of threshold but still got the bad result.
Actually i am encounter same problem in FairMOT, except DeepSort.
I am searching which step make this happen in match stage, have you any suggestion about that,
expect your reply, thanks.

**Comment by MoaazAbdulrahman** [comment]
Hi @xiefengan,
I am facing the same issue. Were you able to solve it? Please let me know. Thanks

**Comment by xiefengan** [comment]
@MoaazAbdulrahman, I found that it's not happened in match stage, the match stage is work well,
because the code will filter out the bounding box which is too wide after the matching stage
you can see **271th line of demo_track.py** ( I am using the imageflow_demo function, maybe other places is the same problem),
you can comment the if statement for all matching bounding box & id will be displayed,
maybe this is helpful for you.

https://github.com/ifzhang/ByteTrack/blob/8b8d9771e89ef1d6aa2ea7b645f26764e33f8b8d/tools/demo_track.py#L236

**Comment by MoaazAbdulrahman** [comment]
@xiefengan Thank you that was really helpful. I have commented out the following line and I am getting better results.
https://github.com/ifzhang/ByteTrack/blob/8b8d9771e89ef1d6aa2ea7b645f26764e33f8b8d/tools/demo_track.py#L271

**Comment by LamnouarMohamed** [comment]
Hi, 

thank you so much for sharing the solution, I have question for you @MoaazAbdulrahman 
do you have commented whole line, or just a part from it ?

thank you so much

**Comment by LamnouarMohamed** [comment]
I have another question relate to yolov5, when I have combined between yolov5 and byteTrack the tracking is bad because contains some transformation "it's necessary for yolox" in our case not necessary can you tell me how do you solve this problem just commented the lines which contains transformations or do you have another solution ?

**Comment by BlueClouDragon** [comment]
Hello @leisurecodog I am facing model problem for detect objects
This bytetrack model only detect person, not detect or track vehicles. but I have some problem in train to detect both person and vehicle. can you introduce me to train the model for this.
