### ISSUE TITLE
Reid Module

### ISSUE THREAD

**Issue by yanghaibin-cool** [ifzhang/ByteTrack#121]
How can we integrate the re-id module for deep features with bytetrack tracker, does it improves the accuracy?

**Comment by Tetsujinfr** [comment]
there is a re-id module in this repo? where?

**Comment by HanGuangXin** [comment]
Same question here. ReID information is important under some conditions, such as camera motion. Also, the paper said there is no improvement when using reID information.
So could you please release the model with ReID module?

**Comment by CaptainEven** [comment]
@Tetsujinfr @HanGuangXin You guys can refer to this repo:
https://github.com/CaptainEven/MCMOT-ByteTrack
Both implement ReID module and multi-class training & testing.

**Comment by Tetsujinfr** [comment]
> @Tetsujinfr @HanGuangXin You guys can refer to this repo: https://github.com/CaptainEven/MCMOT-ByteTrack Both implement ReID module and multi-class training & testing.

Thanks @CaptainEven . Very impressive work. I did not see a mention of reid on your readme thought, but heading there to look at it closer.
