### ISSUE TITLE
怎么训练自己的数据集呢

### ISSUE THREAD

**Issue by xiaoxiaolu1111** [ifzhang/ByteTrack#126]
怎么训练自己的数据集呢

**Comment by huchi00057** [comment]
https://blog.csdn.net/weixin_43429961/article/details/124047461?csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22124047461%22%2C%22source%22%3A%22weixin_44134491%22%7D&ctrtid=KNupJ

評論裡有提及怎麼做~給你參考
