### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/data_path/citypersons.train

### ISSUE THREAD

**Issue by HTCho1** [ifzhang/ByteTrack#137]
Dear authors
I am converting citypersons data to COCO format. However, when running convert_cityperson_to_coco.py, i encounterd FileNotFoundError.
i  have followed your data structure.
In convert_cityperson_to_coco.py, what means DATA_FILE_PATH?
i didn't make 'datasets/data_path/citypersons.train'.
thank you.

**Comment by Ali96528** [comment]
hello HTCho1，have you sloved this problem? I meet the same situation.

**Comment by Ali96528** [comment]
> 

file is here : "datasets/data_path/citypersons.train" in this programme.

**Comment by wenkebei** [comment]
so how to solve this problem? please
