### ISSUE TITLE
colab

### ISSUE THREAD

**Issue by AK391** [ifzhang/ByteTrack#2]
please add a google colab for inference

**Comment by Tetsujinfr** [comment]
@ifzhang I did a colab notebook to run the demo, a modest gift to this wonderful repo / project !
I attach a link [here](https://github.com/Tetsujinfr/Colab_notebooks/blob/main/ByteTrack_Demo.ipynb), as well as a zipped version below.

Feel free to re-use / modify it. @AK391 if you find it useful pls close the issue.

Bye
[ByteTrack_Demo.ipynb.zip](https://github.com/ifzhang/ByteTrack/files/7445495/ByteTrack_Demo.ipynb.zip)

**Comment by ifzhang** [comment]
@Tetsujinfr Thank you very much for the colab demo! We have added it to readme.
