### ISSUE TITLE
Do standard models only support person class?

### ISSUE THREAD

**Issue by bit-scientist** [ifzhang/ByteTrack#207]
First off, thank you for this amazing project. It's really promising.

I have some questions, though. 😄 
It looks like standard models were trained for only person class, right? If I want to track pet animals (cats and dogs) that exist in COCO dataset, can I just use the custom-pretrained YOLOX detector (cat and dog)? You mentioned that one needs to modify byte_tracker.py if s(h)e wants to combine other detectors with BYTE. Could you elaborate what exactly needs to be done? I finding it a little complicated to start. THANK YOU!

**Comment by YamacTan** [comment]
I have a similar problem with the tracker. I just want to use pure YOLOX-X model with 80 classes of COCO for car tracking. But I cannot get the results that I expected.
Did you find any solution about it?

**Comment by Everloom-129** [comment]
So do I, I am trying to find some method for detecting car, but the project is too complex, maybe the team can recommend a part to get start
My starting point: **exps/example/mot/yolox_s_mix_det.py**, is that work? I tried to modify num_classes, but the case don't match

**Comment by bit-scientist** [comment]
Hi, @YamacTan (sorry for the late reply to your message) and @Everloom-129. I can hardly see an activity on this repo. Good news is that [ultralytics ](https://github.com/ultralytics/ultralytics)has integrated [bytetrack ](https://docs.ultralytics.com/modes/track/)into their framework. There you can use bytetrack tracking with any of your custom trained v8 model. Try that and good luck to both of you!

**Comment by Everloom-129** [comment]
Ohhh, I have just realized it yesterday with official help! That's wonderful, thank you for the fantastic model

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
