### ISSUE TITLE
Losing the Tracks even after the detection score is 0.9 

### ISSUE THREAD

**Issue by PranvQT** [ifzhang/ByteTrack#216]
I have a detector which works quite well for the videos that I have.

I am passing these detection to the BYTEtracker as mentioned [here](https://github.com/ifzhang/ByteTrack#combining-byte-with-other-detectors) in the readme "Combining BYTE with other detectors" section. 

`from yolox.tracker.byte_tracker import BYTETracker`
`tracker = BYTETracker(args)`
`for image in images:`
    `dets = detector(image)`
   `online_targets = tracker.update(dets, info_imgs, img_size)`

The detection scores are in the range of **0.8 to 0.95** but still when the human in the video moves , 
the tracker looses the track and assigns new id to that person. 

Can you please tell me what I can do to stop this?

**Comment by danial880** [comment]
@PranvQT how did you solve this issue?

**Comment by PranvQT** [comment]
I tuned the hyper-parameters and that helped..I don't remember exactly which one but there are about 5-6 parameters try changing them ..that should help

> @PranvQT how did you solve this issue?

**Comment by pax7** [comment]
@PranvQT  - can you please paste the numbers you're using right now for those hyper-params?
