### ISSUE TITLE
AssertionError  assert num_gpu <= torch.cuda.device_count()

### ISSUE THREAD

**Issue by iTruffle** [ifzhang/ByteTrack#231]
Thank you for your great job.
I run the code on "Quadro RTX 5000", and successfully get the results of video demo and MOT17 MOT20 datasets.
But, I fail to train on MOT17 and MOT20 datasets. These tracking and training are carried on one environment. 
When I train, I get an error like this:
![image](https://user-images.githubusercontent.com/80766557/178698177-334ec452-d905-4b71-b095-713694250045.png)

And I have checked the informations:
![image](https://user-images.githubusercontent.com/80766557/178698934-185b04f3-8787-4a4c-9fc0-c3049d27b912.png)
![image](https://user-images.githubusercontent.com/80766557/178699029-4e95c72f-8641-4b14-9751-f85ead1f46b8.png)

How can I solve this problem?
Looking forward to your reply?

**Comment by iTruffle** [comment]
I can successfully run the video demo, but fail in training. 

![image](https://user-images.githubusercontent.com/80766557/178699671-588b3e6d-3a2c-4b3b-ae81-4cc693010ede.png)

![image](https://user-images.githubusercontent.com/80766557/178699543-8d4e20ed-e810-4e13-a315-843100e9e690.png)

**Comment by parthmalpathak** [comment]
Try changing - d argument to 0 or 1. It will probably work.

Otherwise try reducing the batch size as well but - d would solve it

**Comment by iTruffle** [comment]
Thank you very much. I have solved this problem.
But when running the code "python3 tools/train.py -f exps/example/mot/yolox_x_mix_mot20_ch.py -d 0 -b 48 --fp16 -o -c pretrained/yolox_x.pth", I meet another error like this:
![image](https://user-images.githubusercontent.com/80766557/178961812-eb4cccc5-7db7-4653-bf0b-59e7384f4be6.png)
![image](https://user-images.githubusercontent.com/80766557/178961857-40cc5b87-ef2a-46fe-8967-8fcfa433ce64.png)
![image](https://user-images.githubusercontent.com/80766557/178962101-27cb5fa7-70c3-4dee-a3ad-3d48f64d1e59.png)
How can I solve this problem?

**Comment by gyh420** [comment]
> Thank you very much. I have solved this problem. But when running the code "python3 tools/train.py -f exps/example/mot/yolox_x_mix_mot20_ch.py -d 0 -b 48 --fp16 -o -c pretrained/yolox_x.pth", I meet another error like this: ![image](https://user-images.githubusercontent.com/80766557/178961812-eb4cccc5-7db7-4653-bf0b-59e7384f4be6.png) ![image](https://user-images.githubusercontent.com/80766557/178961857-40cc5b87-ef2a-46fe-8967-8fcfa433ce64.png) ![image](https://user-images.githubusercontent.com/80766557/178962101-27cb5fa7-70c3-4dee-a3ad-3d48f64d1e59.png) How can I solve this problem?

l have the same question you, how you fix it finally?

**Comment by iTruffle** [comment]
This may be the cuda version is not suitable.
I run with python 3.8  torch 1.11.0+cu113 and torchvision==0.12.0

**Comment by gyh420** [comment]
> This may be the cuda version is not suitable. I run with python 3.8 torch 1.11.0+cu113 and torchvision==0.12.0
thank you, l have fix it
