### ISSUE TITLE
A question about the FPS comparison.

### ISSUE THREAD

**Issue by goldentimecoolk** [ifzhang/ByteTrack#236]
This is an amazing work. But I'm confused with the speed comparison versus other methods. For example, Fairmot reports its FPS based on a 2080 Ti GPU, while bytetrack is based on a V100 GPU. Is the comparison fair?

**Comment by agirbau** [comment]
It's not a fair comparison, not only on the BYTE paper but also on many others. In order to make a fairer comparison, the experiments should be run on the same PC, same specs and GPU, many times and do the average of the runs, but many people just report their times and that's all.

**Comment by goldentimecoolk** [comment]
> It's not a fair comparison, not only on the BYTE paper but also on many others. In order to make a fairer comparison, the experiments should be run on the same PC, same specs and GPU, many times and do the average of the runs, but many people just report their times and that's all.

I got it, thank you!
