### ISSUE TITLE
Is ByteTrack unsuitable when the camera is shaking?

### ISSUE THREAD

**Issue by youngjae-avikus** [ifzhang/ByteTrack#288]
Hello. I'm going to use ByteTrack in a situation where I need to track by installing a camera on the boat
Would ByteTrack be inappropriate in this situation?
Sometimes I have to rely on kalman predictions because inferences don't work well every time. And unfortunately the camera pose is also shaking, but it's not included in the kalman system model, (only x,y,a,h include velocity) so the prediction error seems to be a bit severe. Do you have any suggestions or solutions?

**Comment by youngjae-avikus** [comment]
```python
def multi_predict(self, mean, covariance):
        """Run Kalman filter prediction step (Vectorized version).
        Parameters
        ----------
        mean : ndarray
            The Nx8 dimensional mean matrix of the object states at the previous
            time step.
        covariance : ndarray
            The Nx8x8 dimensional covariance matrics of the object states at the
            previous time step.
        Returns
        -------
        (ndarray, ndarray)
            Returns the mean vector and covariance matrix of the predicted
            state. Unobserved velocities are initialized to 0 mean.
        """
        std_pos = [
            10*self._std_weight_position * mean[:, 3],
            10*self._std_weight_position * mean[:, 3],
            1e-2 * np.ones_like(mean[:, 3]),
            self._std_weight_position * mean[:, 3]]
        std_vel = [
            self._std_weight_velocity * mean[:, 3],
            self._std_weight_velocity * mean[:, 3],
            1e-5 * np.ones_like(mean[:, 3]),
            self._std_weight_velocity * mean[:, 3]]
        sqr = np.square(np.r_[std_pos, std_vel]).T
```

**Comment by youngjae-avikus** [comment]
https://drive.google.com/file/d/134Lya_D3lLHy0gZA7E8vx28EPbcx6AlK/view?usp=share_link

As you can see in the video, when the Inference box is not caught, the prediction value splashes, so I increased the Covariance weight for x,y of std_pos. But when the camera suddenly moved, there was nothing I could do. Is there any way to compensate for this in the current Kalman system modeling?

**Comment by dmlovezh** [comment]
@youngjae-avikus Excuse me! Have u solved this problem yet? Now I also meet this problem, I try a lot, but still does not work.
