### ISSUE TITLE
What is the reason for calculating covariance with mean[3] = height in Kalman filter?

### ISSUE THREAD

**Issue by youngjae-avikus** [ifzhang/ByteTrack#289]
https://github.com/ifzhang/ByteTrack/blob/8d47ea56f4523276eb46386625471afcb11f09d4/yolox/tracker/kalman_filter.py#L107-L116

Why is there a special reason why I took it as a height when modeling?

**Comment by ydm365** [comment]
As indicated by authors' comment, the position array is coded by order x, y, a, h. The forth number(mean[3]) is scale of the bounding box, and I think they assume larger object makes greater movement, and greater dilation or contraction. Actually the other three numbers is independent with scale of objects.

**Comment by youngjae-avikus** [comment]
@ydm365 
In other words, a cov is given to pos that changes in real time in proportion to the object size

**Comment by ydm365** [comment]
> @ydm365 In other words, a cov is given to pos that changes in real time in proportion to the object size

As far as I can tell, this is exactly what the authors are assuming.
