### ISSUE TITLE
[Demo] No bounding box displayed from demo_track.py

### ISSUE THREAD

**Issue by CYJGoh** [ifzhang/ByteTrack#292]
I've followed all the steps mentioned in the [README.md](https://github.com/ifzhang/ByteTrack#readme) of this repo. However, when I tried out the demo using the `demo_track.py` on my machine, no bounding box was shown. The picture below is the snip from the output in the YOLOX_outputs folder. 

![image](https://user-images.githubusercontent.com/63357110/201427369-24b8d6f1-7f34-4d8f-b206-f0efabf385f1.png)

I have used the pre-trained models (particularly the bytetrack_x_mot17 and bytetrack_nano_mot17 models) provided in this repo, and it still gives me the same result. 

When I tried out the Google Colab demo, even with my own model, there were bounding boxes shown in the output.

What seems to be the issue here? Could it be the dependencies issue? Should I reinstall all the dependencies from the start?

**Comment by WinnamonRoll** [comment]
I am facing the same problem.

**Comment by CYJGoh** [comment]
I suspected it was the dependencies issue on my machine; hence, I reinstalled all the dependencies needed for this project in a virtual environment, and everything worked fine. I have attached here the requirements from my virtual env for your reference.

[requirements.txt](https://github.com/ifzhang/ByteTrack/files/10088495/requirements.txt)
