### ISSUE TITLE
How to fine-tune one of the pre-trained models?

### ISSUE THREAD

**Issue by danial880** [ifzhang/ByteTrack#298]
Hi
thanks for the excellent work
Can you please tell me how I can fine-tune the byte track on the custom dataset?
The instructions given in the repository are training the yolox from scratch using pre-trained COCO.
How can I fine-tune one of the pre-trained models?

**Comment by tericalpha** [comment]
@danial880 how you solved this issue?
I need to fine tune the pre trained (byte track default) model

**Comment by danial880** [comment]
> @danial880 how do you solve this issue? I need to fine-tune the pre-trained (byte track default) model

To my understanding, Bytetrack is just a post-processing technique you can use with any tracker. If you want to fine-tune, fine-tune the detector (yolox, yolov7/8) then fine-tune the tracker (centertrack, fairmot, cstracker). After that simply combine your detector and tracker with Bytetrack post-processing.
