### ISSUE TITLE
视频卡顿，追踪目标突然出现远距离位移后，目标出现丢失的问题

### ISSUE THREAD

**Issue by liduowen** [ifzhang/ByteTrack#308]

**Comment by fat-kid** [comment]
加入特征匹配看看？感觉单纯的卡尔曼滤波预测的话，远距离位移以后，应该很难预测到?

**Comment by liduowen** [comment]
是的，从卡尔曼滤波原理角度看确实没办法解决该问题，我换了特征匹配的方式，这个问题已经解决了，非常感谢！

**Comment by SoulProficiency** [comment]
可以github上提供追踪的相关代码吗？

**Comment by Huster-Hq** [comment]
> 是的，从卡尔曼滤波原理角度看确实没办法解决该问题，我换了特征匹配的方式，这个问题已经解决了，非常感谢！

刚接触目标追踪，有一些问题不太懂。bytetrack貌似是一个不需要训练的方法，为什么作者提供train代码？
