### ISSUE TITLE
ValueError: only one element tensors can be converted to Python scalars

### ISSUE THREAD

**Issue by fat-kid** [ifzhang/ByteTrack#316]
![image](https://user-images.githubusercontent.com/42697256/222137595-0510eaf4-b51e-43c7-83ea-ee802e0b9ebb.png)
![image](https://user-images.githubusercontent.com/42697256/222138821-c3877f2a-0195-4b67-8f7b-c2c74a19b18b.png)

as the figure shows that, info_imgs[2] should be one element tensors, but as the debug variable shows that, there are 5 elements in the info_imgs[2], what should I do?  I didn't meet this error when I run the track.py and train.py.

**Comment by Decarryee** [comment]
can you tell me how to fix it?

**Comment by fat-kid** [comment]
> 

try to set these parameters and try again 
 -b 1 -d 1 --fp16 --fuse
I am a little forget how to fix but I can run it now maybe because of these parameters?

**Comment by Decarryee** [comment]
it works, thank you!
