### ISSUE TITLE
Using ByteTrack on other tracker

### ISSUE THREAD

**Issue by NaifahNurya** [ifzhang/ByteTrack#38]
Hi @ifzhang  ,
Thanks for another nice work. I have a question, 
If I want to use ByteTrack for other tracker eg FairMOT, do I need to train the model again, or  can I use arleady trained model?
because I have a model that was trained on FairMOT. So my concern is whether I need to retrain again when I want to use ByteTracker. 

Thank you

**Comment by ifzhang** [comment]
You do not need to train FairMOT again. You can just use your trained FairMOT model and replace of the tracker of FairMOT by ByteTracker.

**Comment by NaifahNurya** [comment]
@ifzhang  Thank you for feedback.
