### ISSUE TITLE
I am trying to setup ByteTrack and I am facing the following issue

### ISSUE THREAD

**Issue by likith1908** [ifzhang/ByteTrack#410]
$ pip3 install -r requirements.txt

Building wheels for collected packages: onnx-simplifier, lap, onnxoptimizer
  Building wheel for onnx-simplifier (setup.py) ... done
  Created wheel for onnx-simplifier: filename=onnx_simplifier-0.3.5-py3-none-any.whl size=12853 sha256=62521612e7c5907464c924e54d274da4f9f8500ced6547bf244a7bcdedbf082e
  Stored in directory: /Users/likithgannarapu/Library/Caches/pip/wheels/f3/62/ad/d33b03db282be8b4a2d86cdf147d2e5f34021e0754ca7eebd0
  Building wheel for lap (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      /private/var/folders/mw/60fg6l4s04b_w2zqvbz38b0c0000gn/T/pip-install-fju15j1i/lap_4870386d32b5416cae4d327df707a4ca/setup.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        from pkg_resources import parse_version
      Partial import of lap during the build process.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/mw/60fg6l4s04b_w2zqvbz38b0c0000gn/T/pip-install-fju15j1i/lap_4870386d32b5416cae4d327df707a4ca/setup.py", line 236, in <module>
          setup_package()
        File "/private/var/folders/mw/60fg6l4s04b_w2zqvbz38b0c0000gn/T/pip-install-fju15j1i/lap_4870386d32b5416cae4d327df707a4ca/setup.py", line 223, in setup_package
          from numpy.distutils.core import setup
      ModuleNotFoundError: No module named 'numpy.distutils'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lap
  Running setup.py clean for lap
  Building wheel for onnxoptimizer (setup.py) ... done
  Created wheel for onnxoptimizer: filename=onnxoptimizer-0.3.13-cp312-cp312-macosx_14_0_arm64.whl size=554212 sha256=a74bd85b7b9ae5c0b740ea83b34d20177e3c184c9401636679443895e8de0bb5
  Stored in directory: /Users/likithgannarapu/Library/Caches/pip/wheels/36/75/fa/11d91817e007f50a1d716a0e5fe977c3990c4701786d7c5a04
Successfully built onnx-simplifier onnxoptimizer
Failed to build lap
ERROR: Could not build wheels for lap, which is required to install pyproject.toml-based projects

**Comment by LoneDragonII** [comment]
your issue is with building lap. install numpy matplotlib etc first manually then install lap==0.4.0 and then run the requirements install again. this is how i fixed it if the issue still persists you can lower your python version and try again. or you can try what this guy suggests as well this worked for me on python 3.10.12.
https://github.com/gatagat/lap/issues/45#issuecomment-1656993924

**Comment by likith1908** [comment]
Thanks!!
