### ISSUE TITLE
TensorRT-cpp代码中BYTETracker::BYTETracker的三个阈值参数

### ISSUE THREAD

**Issue by FunnyWii** [ifzhang/ByteTrack#418]
作者您好，我是个MOT入门新人。。
读完了您的论文，参数似乎只提到了`high_thresh`是0.6啊，请问另外两个参数的作用是什么呢？
通过测试，发现`match_thresh`会影响匹配的结果，如果调低，目标的ID会产生频繁的IDS。
但是`track_thresh`是什么作用可以解答一下吗

```
track_thresh = 0.5;
high_thresh = 0.6;
match_thresh = 0.8;
```

**Comment by wujiazong** [comment]
track_thresh 是低置信度的选取阈值，低于这个阈值，检测框直接就不跟踪了。
match_thresh  是前帧和后帧IOU的匹配阈值，若出现（1-IOU） > match_thresh,则直接跟踪失败。
 具体来说，前帧与后帧的 每个经过track_thresh 和high_thresh 筛选 后的边界框，都会两两之间计算IOU，形成一个关于IOU的代价矩阵，代价矩阵表示边界框之间的接近程度，数值越接近0，说明边界框的相似度越高。
使用匈牙利算法（lapjv）对代价矩阵进行加速求解，得到前帧与后帧最匹配的边界框，并认为是同一个ID。

**Comment by FunnyWii** [comment]
> track_thresh 是低置信度的选取阈值，低于这个阈值，检测框直接就不跟踪了。 match_thresh 是前帧和后帧IOU的匹配阈值，若出现（1-IOU） > match_thresh,则直接跟踪失败。 具体来说，前帧与后帧的 每个经过track_thresh 和high_thresh 筛选 后的边界框，都会两两之间计算IOU，形成一个关于IOU的代价矩阵，代价矩阵表示边界框之间的接近程度，数值越接近0，说明边界框的相似度越高。 使用匈牙利算法（lapjv）对代价矩阵进行加速求解，得到前帧与后帧最匹配的边界框，并认为是同一个ID。

感谢！
