### ISSUE TITLE
多线程交互，当一个QThread线程的run函数释放后，再次建立新线程的run函数，Track_id计数会递增，新线程的Track_id计数会是上一次线程的最大Track_id计数开始，不是1

### ISSUE THREAD

**Issue by GIBEREZ** [ifzhang/ByteTrack#419]
![QQ截图20240911003937](https://github.com/user-attachments/assets/7a871278-5bd4-4444-8d74-8ab50434164a)

**Comment by Pi-Boss** [comment]
改源码即可  里面的next_id 直接在函数内部用static声明了

**Comment by GIBEREZ** [comment]
> 改源码即可 里面的next_id 直接在函数内部用static声明了

感谢解答，11月了，hhh有点历史老坑了这帖子
