### ISSUE TITLE
[Err occured when test] 

### ISSUE THREAD

**Issue by CaptainEven** [ifzhang/ByteTrack#46]
File "tools/track.py", line 18, in <module>
    from yolox.evaluators import MOTEvaluator
ImportError: cannot import name 'MOTEvaluator' from 'yolox.evaluators'

**Comment by dhruvsangal9** [comment]
How did you resolve it please tell

**Comment by songxia928** [comment]
run this command：
'''
pip uninstall yolox

cd tools
ln -s ../yolox 
'''
