### ISSUE TITLE
Weird paths after mix_det

### ISSUE THREAD

**Issue by pedromoraesh** [ifzhang/ByteTrack#58]
Hello Guys, nice work btw.

I'm training a tiny and nano version, using the mixed data.
I got a lot of errors, after debugging I realize that paths from Cityscapes were cropped at some point and ETHZ was added to a folder called ets.

https://github.com/ifzhang/ByteTrack/blob/9e5efb7bc237ea2c33ecbd1e29ba5cc99f09c1e7/yolox/data/datasets/mot.py#L101

After printing the `img_file` i got the following paths:

- ByteTrack/datasets/mix_det/cp_train/**tyscapes**/images/train/hamburg/hamburg_000000_027304_leftImg8bit.png
- ByteTrack/datasets/mix_det/ethz_train/**ets**/ETHZ/eth01/images/image_00000908_0.png

Yes, I did all the steps described in the mix_xx.py file (mkdir, ln -s...), everything ran like a charm, except those weird paths.

After creating those folders I was able to train but didn't find where the path is written.

**Comment by MasterBin-IIAU** [comment]
@pedromoraesh Hi, we have made a small [change](https://github.com/ifzhang/ByteTrack/commit/b82ba6170d439a4a0d970cfe8c43e5a69ce99b7f) to the conversion script of ETHZ and Citypersons. Maybe it can give you some help :)
