### ISSUE TITLE
Question about bytetrack+ReID

### ISSUE THREAD

**Issue by WooXinyi** [ifzhang/ByteTrack#63]
Thanks for your excellent work! Could you please release the combined codes of  bytetrack and ReID?

**Comment by ifzhang** [comment]
We can find the combination of BYTE and ReID in the [FairMOT tutorials](https://github.com/ifzhang/ByteTrack/blob/main/tutorials/fairmot/tracker.py).

**Comment by WooXinyi** [comment]
> We can find the combination of BYTE and ReID in the [FairMOT tutorials](https://github.com/ifzhang/ByteTrack/blob/main/tutorials/fairmot/tracker.py).

thanks a lot！i will check that
