### ISSUE TITLE
What is format of input and output bbox to BYTETracker?

### ISSUE THREAD

**Issue by iamrajee** [ifzhang/ByteTrack#69]
I'm using ByteTracker on top of yolov3_detection, but getting the wrong tracking bbox result.

![Screenshot from 2021-11-11 19-26-59](https://user-images.githubusercontent.com/25712145/141311841-09ffb919-bea0-4972-93ab-1dbefce53d49.png)
_Observation: In above image bottom-right of wrong-bbox corresponds to the top-left of true-bbox._
My input dets bbox format is as[bbox.xmin, bbox.ymin, bbox.xmax, bbox.ymax, bbox.probability]

and expecting the output bbox in the same format. **Am I doing something wrong?** Do I need to normalise bbox at any point of time?

I tried to shuffle around in format as `[bbox.xmax, bbox.ymax, bbox.xmin, bbox.ymin, bbox.probability]` but it din't helped.

Here is the [code](https://gist.github.com/iamrajee/ce01ace31f0324fd222cb66761be0e8b) I'm using for tracking(It's ROS python script)

When I use [sortTracker](https://gist.github.com/iamrajee/fd690c34a38780f98f7016e41121c436) on top of same yolov3_detection, I get perfect results as expected
![Screenshot from 2021-11-11 20-03-03](https://user-images.githubusercontent.com/25712145/141315761-4ea98aca-401d-425c-be7c-aa655dcd2cb8.png)
:

**Comment by iamrajee** [comment]
After some tinkering, I got the desired result.
I turns out that I had use it like this;

```
self.bytetracker = BYTETracker(self.args)
online_targets = self.bytetracker.update(dets, [800,800], self.exp.test_size)
for t in online_targets:
                tlwh = t.tlwh
                tid = t.track_id
                vertical = tlwh[2] / tlwh[3] > 1.6
                if tlwh[2] * tlwh[3] > mot_tracker.args.min_box_area and not vertical:
                    online_tlwhs.append(tlwh)
                    bbox.xmin = tlwh[0]
                    bbox.ymin = tlwh[1] 
                    bbox.xmax = tlwh[0] + tlwh[2]
                    bbox.ymax = tlwh[1] + tlwh[3]
```

**Comment by tungdop2** [comment]
> 

Hello, how can I put yolov5 detection to the code?
