### ISSUE TITLE
Deleting known tracks for new videos

### ISSUE THREAD

**Issue by dumbPy** [ifzhang/ByteTrack#79]
I am creating a new BYTETracker object for each video, but the tracking_ids seem to be increasing over videos. I suppose there is some sort of module level cache that I need to delete, so the track ids start from 0 for each video?

**Comment by rusvagzur** [comment]
Hi @dumbPy did you find a solution for this?

**Comment by dumbPy** [comment]
@rusvagzur  No I did not. Didn't check on it for some time now, but will paste it here if I find something in future.

**Comment by voldemortX** [comment]
@dumbPy I also experience similar problem and don't know the reason. Do you think this will result in cross-video matching and affect performance?

**Comment by voldemortX** [comment]
@rusvagzur @dumbPy  I think I found the issue, shared class static attributes can't be resetted by __init__(). But somehow BYTE is robust enough to be unaffected in performance. 

https://github.com/ifzhang/ByteTrack/blob/f1eaccd86756e8b0b596ae0e5569b51e90e6b967/yolox/tracker/basetrack.py#L36

A simple reproduction:

```
class Track(object):
    id = 0

    def __init__(self):
        pass

    def update(self):
        Track.id += 1
        print(Track.id)


for i in range(5):
    t = Track()
    t.update()

```

```
1
2
3
4
5
```

**Comment by dumbPy** [comment]
Thanks for looking into it @voldemortX 
Have raised #190

**Comment by HanGuangXin** [comment]
@voldemortX I don't think the exact number of id will affect the final metrics, as long as that number is kept the same during tracking. 

What do you think of this explanation?

**Comment by voldemortX** [comment]
> @voldemortX I don't think the exact number of id will affect the final metrics, as long as that number is kept the same during tracking. 
> 
> What do you think of this explanation?

Yes I agree that tracking performance in term of e.g. HOTA/MOTA will not be affected.

**Comment by HanGuangXin** [comment]
> > @voldemortX I don't think the exact number of id will affect the final metrics, as long as that number is kept the same during tracking.
> > What do you think of this explanation?
> 
> Yes I agree that tracking performance in term of e.g. HOTA/MOTA will not be affected.

Agreed.
