### ISSUE TITLE
MOT17 results in NaN

### ISSUE THREAD

**Issue by NarutoZhao** [ifzhang/ByteTrack#80]
Hi, hello, according to your steps, the results are shown below
![image](https://user-images.githubusercontent.com/32025355/142338457-2dfb3ae0-720d-444d-b1ab-964f8c9d5c53.png)
![image](https://user-images.githubusercontent.com/32025355/142338487-93c16a62-9591-4be8-8ce8-33b4e75b6585.png)

**Comment by NarutoZhao** [comment]
Track gt is this 'datasets/mot/train/*/gt/ gt_val_half-txt '
but，I haven't figured out how to make this yet, am I missing something?

**Comment by NarutoZhao** [comment]
@ifzhang

**Comment by NarutoZhao** [comment]
It was my fault. I took the wrong path

**Comment by xiaomujiang** [comment]
> Track gt is this 'datasets/mot/train/*/gt/ gt_val_half-txt ' but，I haven't figured out how to make this yet, am I missing something?

i have the same problem, which wrong path do you say
