### ISSUE TITLE
I got the bad results of mota and idf1,ask for help online!!!

### ISSUE THREAD

**Issue by yanghaibin-cool** [ifzhang/ByteTrack#81]
The configuration of my computer: an 11G video memory 2080Ti.
Due to limited computer resources, I finally chose yolox_m model as my baseline, where I set -d=1,-b=4 and ran the following training commands:
python3 tools/train.py -f exps/example/mot/yolox_m_mix_det.py -d 1 -b 4 --fp16 -o -c pretrained/yolox_m.pth
After 80 Epochs, I got the following training results:
![image](https://user-images.githubusercontent.com/72022193/142796136-13f7d01e-7533-4712-9484-1234bee0bd91.png)
![image](https://user-images.githubusercontent.com/72022193/142795426-20f36f74-fec9-4fd1-9aaa-7e5697282824.png)
![image](https://user-images.githubusercontent.com/72022193/142795445-d7ca321b-bc24-4fec-9c08-4882a477e6c1.png)
This is a bad training result for me.Because I did not get the indicators in the following table, especially MOTA and IDF1.
![image](https://user-images.githubusercontent.com/72022193/142795575-132499f4-28be-405f-9fb4-135681ad13c4.png)
So I downloaded the corresponding weights in the table and compared the evaluation results, and found that my detector was not well trained. I don't know the reason, is it batch_size=4?
I hope to know why this is this, and what can I do in order to get an indicator in the table?
I hope to get your reply.Thank you. @ifzhang

**Comment by yanghaibin-cool** [comment]
Sorry.Because the table is not clear, upload a piece.

![image](https://user-images.githubusercontent.com/72022193/142796580-417b67c9-da87-4bfa-b70b-3a1a79835738.png)

**Comment by TheMadScientiist** [comment]
@yanghaibin-cool Hi, how did you get tensorboard to work with the bytetrack training? I'm having trouble with this.
