### ISSUE TITLE
Can this run without onnx-simplifier?

### ISSUE THREAD

**Issue by lpkoh** [ifzhang/ByteTrack#85]
Hi,

I am trying to test the program on my Jetson, which does not support installation of onnxoptimizer and hence onnx-simplifier. I see that this is in requirements. Can I still run the demo without it?

**Comment by lpkoh** [comment]
It works.

**Comment by nolandg** [comment]
@lpkoh May I ask which Jetson are you running on? Nano? NX? TX2? What kind of frame rates did you get?
Thanks!
