### ISSUE TITLE
Bounding boxes for STracks not updating using other detector

### ISSUE THREAD

**Issue by zapu222** [ifzhang/ByteTrack#95]
Hello,
I am attempting to use BYTE with a version of YOLOv5 but cannot get it to work properly. I am passing the detection results to BYTETracker but the output of the tracker throughout the whole video is just the predicted bounding box from the first frame. It is as if the STrack object is not updating according to the new YOLOv5 detections. Any ideas about what I am doing wrong? I am using a track_thresh=0.65 and match_thresh=0.65.

**Comment by gmt710** [comment]
Hello, Have you solved this ?

**Comment by zapu222** [comment]
I have yes! It was a mistake on my end

**Comment by tungdop2** [comment]
I downloaded yolov5x6.pt to  pretrained folder, and after running train.py, I got ModuleNotFoundError: No module named 'models'. How to fix it?
